[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  targetPort = 8080
  port = 3000
  publish = "dist"
  autoLaunch = true
  framework = "#custom"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "cors", "twilio", "serverless-http"]